clflushopt/tpchgen-rs

data/csv/README.md
- Related to  https://github.com/clflushopt/tpchgen-rs/pull/11
Here are some instructions on how to reproduce and compare the results of the data generator. I have found a few discrepancies with this method that I will file as a follow on ticket
=> Add instructions for verifying checked in results

.github/workflows/conformance.yml, tests/conformance.sh, tpchgen-cli/Cargo.toml, tpchgen-cli/src/main.rs, tpchgen/src/dates.rs, tpchgen/src/distribution.rs, tpchgen/src/generators.rs
Scaffold a CLI experience that matches `dbgen`, while we don't have to match it 100% we will strive for conformance so we can ideally be used as a drop in replacement.
- related to https://github.com/clflushopt/tpchgen-rs/issues/9
=> feat: scaffold basic dbgen like api

tests/conformance.sh
=> feat: Update conformance test to run at scale factors up to 1

CONTRIBUTING.md
Basic contributor's guide nothing special, feel free to suggest improvements.
=> feat: Create CONTRIBUTING.md

tpchgen/src/generators.rs, tpchgen/src/random.rs
=> feat: Derive Debug for all generator and iterator types

tpchgen/src/dates.rs
This change introduces a lookup table that's built on first access for julian date format used when generating the lineitem table. The optimization eliminates a path that we spend about 14% of total running time in (profile sampled).
Here's a before profile where 14% of the time was spent calling `julian`.
An after profile with the block entirely gone due to lazily initializing it once and using a lookup table for the rest of the dates.
The trade-off here is entirely about moving runtime CPU cost to memory which is not a lot (I estimated about 9 KiB from `4 * 2557` where 2557 is the number of `i32`'s we store in the lookup table.
Below are the timings captured from `main` and this branch on an 9950X workstation (single core used)  from a `release` build.
`main` :
``` …
```
=> feat: Use lookup tables for julian date format (3-5% improvement)

tpchgen/src/text.rs
- Part of https://github.com/clflushopt/tpchgen-rs/issues/56
More random things I noticed while trying to make startup faster. I will comment in line
Performance:
```
time target/release/tpchgen-cli -s 0.001 --tables=line-item --output-dir=/tmp/tpchdbgen-rs
```
| main | 0m0.960s |
| this branch | 0m0.833s | 
The biggest change is to avoid an N^2 algorithm in text generation that I noticed while looking at the flamegraph
=> Speed up initial TextPool generation more (15% faster)

tpchgen/src/csv.rs
=> fix: quote columns that may contain comma for csv output

tpchgen-cli/src/main.rs
`generate_in_chunks` now already buffers data in large mutli-MB memory buffers
Using `BufWriter` when writing such chunks simply results in copying the data again. Let's not use the buf write when possible
I noticed this while doing profiling on https://github.com/clflushopt/tpchgen-rs/issues/76
There were 32 buffers allocated instead of just 16 (for each core). 
After this change I verified that there are only 16 x 16mB buffers (so it saves about 100MB of peak memory use)
I also measured performance by generating LineItem SF 100 (80GB of data) and I saw a slight increase (the numbers fluctuated a bit so I am not sure how real)
| branch | Speed | Time |
| Main |  (3.04 GB/sec) | 24.5 | 
| This PR | (3.22 GB/sec) | 23.2 | 
Main
```shell …
```
=> Avoid double buffering when writing CSV/TBL

tpchgen-cli/src/main.rs
- Closes https://github.com/clflushopt/tpchgen-rs/issues/81
I verified I can generate parquet SF 1000 now without error using this command
I tested with this command:
```
RUST_LOG=debug cargo run --release -- -s 1000 --format=parquet --tables=line-item --stdout > /dev/null
```
With this fix, we will be in the position to actually benchmark and produce some charts :)
=> Limit number of parquet row groups

Cargo.toml, tpchgen-cli/Cargo.toml, tpchgen/Cargo.toml
Aligns all the workspaces to inherit some workspace level configuration.
=> fix: Align all manifest files to use workspace level configuration for v0.1.0

README.md
Some small minor README improvements
=> fix: minor README improvements

tpchgen/src/dates.rs
- Follow on to https://github.com/clflushopt/tpchgen-rs/pull/97
The comments still refer to to Arrow even though the code is now in tpchgen, so let's tweak the comments
=> chore: tweak doc comments, add `inline` for good measure

tpchgen-arrow/Cargo.toml
=> feat: pin chrono package to 0.4.39

README.md
I added a link to @alamb 's awesome demo and blog post in the README.
=> feat: Link to @alamb's demo and blog in README

README.md, tpchgen-arrow/README.md, tpchgen-cli/Cargo.toml
- Part of #101 
Here are some small documentation tweaks
=> Documentation tweaks

tpchgen-cli/README.md
Copy/paste new `tpchgen-cli -h`
=> [feat] update tpchgen-cli's README

.github/workflows/tpchgen-cli-publish-pypi.yml
Part of #132
Change github action to publish to pypi
=> [feat] publish to pypi

tpchgen/src/distribution.rs, tpchgen/src/text.rs
Replaces `ByteArrayBuilder` with a plain old `Vec`.
The goal was faster text pool creation. I thought avoiding zeroing out the vec would be more significant. But there's almost no change. I do think using a `Vec` and reducing some of the abstraction around this can help future optimization work though.
Vast majority of the time is still spent on `memmove`. I think there's a path towards doing fewer larger batches for `memmove` instead of the many small calls we're doing now. But that'd need to be in a followup at some point.
Perf changes within noise threshold. Ran three times with each branch with small sf to test text pool initialization.
```
time target/release/tpchgen-cli -s 0.01 --output-dir=/tmp/tpchdbgen-rs
```
| main | this branch |
|-|-|
| 1.017 secs, 1.022 secs, 1.023 secs | …
=> Replace ByteArrayBuilder with Vec

Cargo.toml, tpchgen-arrow/Cargo.toml, tpchgen-cli/Cargo.toml
Upgrades all crates to v1.1.0 see the release pages for a change log.
P.S: This will be the last pull request I will make for the next month or two as I will be focusing next on the Datafusion integration and the planning/work for Datafusion join query optimizer roadmap. I will be actively fixing any new issues, reviewing PRs and such just won't be able to address some feature requests.
=> feat: prepare v1.1.0

tpchgen-cli/tests/cli_integration.rs
- This is a small follow on to https://github.com/clflushopt/tpchgen-rs/pull/156
I noticed it took a while for the cli test to run, so let's use multiple threads
Before (15.6 s)
```
(venv) andrewlamb@Andrews-MacBook-Pro-3:~/Software/tpchgen-rs$ cargo nextest  run --test cli_integration
Compiling tpchgen-cli v1.1.1 (/Users/andrewlamb/Software/tpchgen-rs/tpchgen-cli)
Finished `test` profile [unoptimized + debuginfo] target(s) in 0.47s
────────────
Nextest run ID 18ce3d74-1627-4f9c-b38d-4bf935ff9959 with nextest profile: default
Starting 3 tests across 1 binary
PASS [   4.325s] tpchgen-cli::cli_integration test_tpchgen_cli_tbl_scale_factor_0_001
PASS [   8.126s] tpchgen-cli::cli_integration test_write_parquet_orders
PASS [  15.685s] tpchgen-cli::cli_integration test_tpchgen_cli_parts
``` …
=> Minor: parallelize cli part validation test

ARCHITECTURE.md
I was reading some docs and noticed a few improvements that could be made to the architecture docs (like the addition of the tpchgen-arrow crate)
=> Minor: Update ARCHITECTURE.md
