tpchgen/src/generators.rs, tpchgen/src/random.rs, tpchgen/src/text.rs
- part of https://github.com/clflushopt/tpchgen-rs/issues/6
- As shown in https://github.com/clflushopt/tpchgen-rs/pull/17, recomputing the TextPool requires several seconds, so doing it once for all tables improves performance significantly
This PR changes
1. Use a single `Arc<TextPool>`  that is initialized once per process
2. Avoid copying the `Vec<u8>` on creation
=> feat: Create `TextPool` once per process rather than once per table

tpchgen/src/generators.rs, tpchgen/src/random.rs, tpchgen/src/text.rs
- Part of https://github.com/clflushopt/tpchgen-rs/issues/6
The overall plan is described [here](https://github.com/clflushopt/tpchgen-rs/issues/6#issuecomment-2728967340). I am trying to make these PRs easy to review by making them in chunks.
Several of the data generators currently return `String` which forces a copy. The data generator then copies the data again into the output immediately, so avoiding the intermediate copy makes things faster. 
1. Update the generators as much as possible to avoid creating `String`s . 
2. Avoid UTF-8 validation on known ASCII data 
This PR actually does make things a bit faster (but most of the data is still turned into a String by the iterators), but in future PRs I will change the iterators so they do not use Strings either. 
I will comment more …
=> Change Random* generators to return `&str` or structs rather than `String` (10% faster)

Cargo.toml, tpchgen-cli/src/main.rs, tpchgen/src/dates.rs, tpchgen/src/distribution.rs, tpchgen/src/generators.rs, tpchgen/src/random.rs, tpchgen/tests/integration_tests.rs
Part of #6 this change introduces several, small optimizations that compound at large scale factors (1+).
- Refactor `RandomStringSequence` to allocate the values vector only once instead of per call to `next_value()` and inline the randomness swapping logic to be on indices to avoid mutating the original vector, below you can see the profile.
**Before**
**After**
=> feat: optimize single threaded performance

tpchgen/src/dates.rs, tpchgen/src/generators.rs
- Similarly to https://github.com/clflushopt/tpchgen-rs/pull/26
- Part of https://github.com/clflushopt/tpchgen-rs/issues/6
The overall plan is described [here](https://github.com/clflushopt/tpchgen-rs/issues/6#issuecomment-2728967340). I am trying to make these PRs easy to review by making them in chunks.
Several of the data generators represent Dates using a `String` which forces a copy. The data generator then copies the data again into the output immediately, so avoiding the intermediate copy makes things faster. 
1. Use a TPCHDate type rather than a string to represent dates
This PR also improves performance on its own (so when combined with https://github.com/clflushopt/tpchgen-rs/pull/26 we are already significantly better)
Performance (of `target/release/tpchgen-cli -s 1 …
=> Change date handling to use TPCHDate type rather than String (10% faster)

.github/workflows/rust.yml, tpchgen/src/distribution.rs, tpchgen/src/generators.rs, tpchgen/src/random.rs, tpchgen/src/text.rs
Runs `cargo clippy` and `cargo clippy` as a preamble during the Rust action in CI + I addressed a few linter issues clippy raised.
=> feat: Add fmt + clippy to the build action

tpchgen-cli/src/main.rs, tpchgen/src/generators.rs, tpchgen/tests/integration_tests.rs
- Part of https://github.com/clflushopt/tpchgen-rs/issues/6
My overall plan is described [here](https://github.com/clflushopt/tpchgen-rs/issues/6#issuecomment-2728967340), and I am trying to make PRs easy to review by making them in chunks
Creating `String` is expensive:
1. The bytes must be copied
2. The overhead of allocation/deallocation is substantial.
Thus the fewer `String`s created the faster the data generator goes
Once we are happy with this pattern, I plan to apply the same thing to the other 6 tables
Rework how `LineItem`'s are generated to avoid creating / copying`String`
Testing with
```shell
time target/release/tpchgen-cli -s 1 --output-dir=/tmp/tpchdbgen-rs
```
| `main` | 0m8.579s |
| this PR | 0m6.985s |
I tried several times to keep …
=> Avoid copying `String` when generating `LineItem` (20% faster)

tpchgen/Cargo.toml, tpchgen/src/dates.rs
Removes an extra dep, using stdlib's version.
=> Remove lazy_static dep, replace with std::sync::LazyLock

tpchgen/src/distribution.rs, tpchgen/src/generators.rs, tpchgen/src/text.rs
Closes https://github.com/clflushopt/tpchgen-rs/issues/42
Passes references to generators instead of each creating the default one.
The goal of this change is to remove needing to hang onto the generator after creating the iterator (since it owned the distribution data).
Retains the `'static` semantics for all `new` methods on the generators.
=> Pass distribution references to generators

tpchgen/src/generators.rs, tpchgen/src/random.rs
This PR avoids one string allocation and one string copy for each Address generated.
Only `SUPPLIER` and `CUSTOMER` have addresses, so the impact on overall performance is limited but measurable.
Performacnce
```shell
time target/release/tpchgen-cli -s 1 --output-dir=/tmp/tpchdbgen-rs
```
| main | 0m6.658s |
| this PR | 0m6.452s (3% faster)| 
```shell
time target/release/tpchgen-cli -s 100 --tables customer --output-dir=/tmp/tpchdbgen-rs
```
| main | 0m12.558s |
| this PR | 0m11.297s (11% faster) |
=> Avoid copying strings for Addresses (10% faster for customers, 3% faster overall)

tpchgen-cli/src/main.rs, tpchgen/src/generators.rs, tpchgen/src/random.rs, tpchgen/tests/integration_tests.rs
- Part of https://github.com/clflushopt/tpchgen-rs/issues/10
This PR removes some more
1. Consolidates format strings in the cli and tests to use the `Display` impl 
2. Avoids some more String copies by postponing formatting
Performance of running
```shell
time target/release/tpchgen-cli -s 1 --output-dir=/tmp/tpchdbgen-rs
```
| main | 0m6.637s |
| this PR | 0m6.265s |
=> Remove more String copying (5% faster)

tpchgen/src/decimal.rs, tpchgen/src/generators.rs, tpchgen/src/lib.rs
- Closes https://github.com/clflushopt/tpchgen-rs/issues/44
Opted to go for i64 for the internal representation since a few of the existing float were being created from computations on table keys (i64).
=> Add decimal type, avoid floating point calculations (7% faster)

tpchgen/src/generators.rs
It wasn't clear to me that the lifetimes on the Generators introduced by @scsmithr  in the following PR is `'static`
- https://github.com/clflushopt/tpchgen-rs/pull/35
Thus I would like to make this more explicit by adding some comments
=> Make `'static` lifetime explicit in Generators

ARCHITECTURE.md, README.md, tpchgen/Cargo.toml, tpchgen/data/README.md
@scsmithr @clflushopt and I were discussing the crates design here: https://github.com/clflushopt/tpchgen-rs/issues/46#issuecomment-2738433070
I wanted to capture the consensus in documentation. 
Please let me know if I got it right
=> Add `ARCHITECTURE.md` documentation with design goals (keep data generator crate dependencies minimal)

tpchgen/src/dates.rs, tpchgen/src/decimal.rs, tpchgen/src/random.rs
Inspired by @scsmithr's comments https://github.com/clflushopt/tpchgen-rs/pull/50#pullrequestreview-2702915563
We now have date and decimal so called "newtype" wrappers around `i32`/`i64` that allow formatting into a single location
Right now it is easy to go from `i32` -> newtype, but not the other way around
Typically, there is a function in rust programs `into_inner` that does the conversion.
We could also consider adding `From` impls, but I think these functions are more explicit and we can add from impls later
I also added some more `derive` traits while I was at it
=> Add `into_inner` for wrapper types, and derive some more traits`

tpchgen-cli/src/main.rs, tpchgen/src/csv.rs, tpchgen/src/lib.rs
Add ability to print tpch tables as csv files
- closes https://github.com/clflushopt/tpchgen-rs/issues/53
This is a step towards parallel generation and parquet output
I also verified you can query these files from datafusion-cli. A teaser:
```sql
> select * from '/tmp/tpchdbgen-rs/lineitem.csv' limit 10;
+------------+-----------+-----------+--------------+------------+-----------------+------------+-------+--------------+--------------+------------+--------------+---------------+-------------------+------------+-------------------------------------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_quantity | l_extendedprice | l_discount | l_tax | l_returnflag | l_linestatus | l_shipdate | l_commitdate | l_receiptdate | l_shipinstruct    | l_shipmode | l_comment …
```
=> Implement output as CSV

tpchgen/Cargo.toml, tpchgen/src/distribution.rs
- Part of https://github.com/clflushopt/tpchgen-rs/issues/56
- Closes https://github.com/clflushopt/tpchgen-rs/pull/59
This PR is based on great work from @scsmithr  in https://github.com/clflushopt/tpchgen-rs/pull/59 and makes initial Distribution loading time 2x faster. 
The key change is to loading Distributions so the names are resolved once on load rather than on each access. 
This significantly speeds up the startup time
Testing with
```shell
time target/release/tpchgen-cli --tables line-item -s 0.001 --output-dir=/tmp/tpchdbgen-rs
```
| Header | Header |
| main | 0m2.036s |
| this branch | 0m0.985s |
=> Remove  hashmap lookups in distribution creation, remove IndexMap dependency (2x startup time speedup)

tpchgen/Cargo.toml, tpchgen/src/distribution.rs
Partially addresses https://github.com/clflushopt/tpchgen-rs/issues/56
Also removes IndexMap
Wip. The timings are down, but there might be alternative approaches here that I may try to explore.
This approach would also remove some flexibility with what we allow in a distribution, but I don't think that matter for this.
```
$ time cargo run --release -- -s 0.01 --output-dir=/tmp/tpchdbgen-rs-001
```
Tiny SF to capture the initialization time, not actual data generation.
`main`: 2.851s, 2.694s, 2.764s
this branch: 1.860s, 1.867s, 1.864s
=> (POC): Remove some hashmap lookups in distribution lookup

tpchgen/src/distribution.rs, tpchgen/src/random.rs
- Part of #56 
This PR avoids copying / creating `String`s while loading the inital distributions,
It yields a small but measurable 2% improvement
Timings
```
time target/release/tpchgen-cli --tables line-item -s 0.001 --output-dir=/tmp/tpchdbgen-rs
```
| main | 0m0.973s |
| this pr | 0m0.952s |
=> Avoid String creation while loading `Distributions` (2% less startup time)

tpchgen-cli/Cargo.toml, tpchgen-cli/src/csv.rs, tpchgen-cli/src/generate.rs, tpchgen-cli/src/main.rs, tpchgen-cli/src/sources.rs, tpchgen-cli/src/tbl.rs, tpchgen/src/csv.rs, tpchgen/src/generators.rs, tpchgen/tests/integration_tests.rs
- closes https://github.com/clflushopt/tpchgen-rs/issues/10
- closes https://github.com/clflushopt/tpchgen-rs/pull/34
- builds on https://github.com/clflushopt/tpchgen-rs/pull/54
Features:
1. Logging support via `-v` and `RUST_LOG`
2. Parallel generation for all tables
3. No new dependencies on the tpch core crate and minor changes
In single threaded mode, the generator can create 250MB/sec with each core which is 4GB/s on my 16 core laptop
This scales linearly with 
Here are performance measurements for SF=100 on my Mac M3 (with 16 cores)
| branch | speed | speed (writing to /dev/null) |
|--------|--------|--------|
| main | 6m1.984s | N/A
| this branch | 1m0.099s | 0m28.732s | 
```shell
time target/release/tpchgen-cli -s 100 --output-dir=/tmp/tpchdbgen-rs
```
It actually turns out this …
=> Parallel output in tpchgen-cli (Nx faster, where N is number of cores)

tpchgen-arrow/src/conversions.rs, tpchgen-arrow/src/customer.rs, tpchgen-arrow/src/lib.rs, tpchgen-arrow/src/lineitem.rs, tpchgen-arrow/src/nation.rs, tpchgen-arrow/src/order.rs, tpchgen-arrow/src/part.rs, tpchgen-arrow/src/partsupp.rs, tpchgen-arrow/src/region.rs, tpchgen-arrow/src/supplier.rs, tpchgen-arrow/tests/reparse.rs, tpchgen-cli/src/csv.rs, tpchgen-cli/src/main.rs, tpchgen-cli/src/tbl.rs, tpchgen/src/csv.rs, tpchgen/src/generators.rs, tpchgen/src/random.rs, tpchgen/tests/integration_tests.rs
- part of https://github.com/clflushopt/tpchgen-rs/issues/46
- Follow on to https://github.com/clflushopt/tpchgen-rs/pull/71
1. Implements table --> Arrow conversion for the remaining TPCH tables
2. Adds test coverage
It is mostly a mechanical (but large) PR
=> Implement arrow conversion for remaining tables

tpchgen-cli/Cargo.toml, tpchgen-cli/src/generate.rs, tpchgen-cli/src/main.rs, tpchgen-cli/src/parquet.rs, tpchgen-cli/src/statistics.rs, tpchgen/Cargo.toml
- Closes #46 
This PR adds the ability to write directly generate parquet files using all available cores with minimal buffering
Among other things it can generate the entire TPCH SF 100 dataset in less than a minute and less than 400MB peak memory usage (as measured by top).
My measurements show it can do about 0.5 G/sec for `ZSTD` parquet
Example
```shell
andrewlamb@Andrews-MacBook-Pro-2:~/Software/tpchgen-rs$ time target/release/tpchgen-cli -v --scale-factor=100 --format=parquet --output-dir=/tmp/repo
[2025-03-28T00:30:52Z INFO  tpchgen_cli] Verbose output enabled (ignoring RUST_LOG environment variable)
[2025-03-28T00:30:53Z INFO  tpchgen_cli] Created static distributions and text pools in 806.286541ms
[2025-03-28T00:30:53Z INFO  tpchgen_cli] Writing table nation (SF=100) to …
```
=> Support writing directly to parquet files

tpchgen-cli/src/parquet.rs
- Related to https://github.com/clflushopt/tpchgen-rs/issues/81
If the generators get a panic, stop early, don't keep trying to write
On main when I hit the error I get many errors about not being able to write
```
thread 'tokio-runtime-worker' panicked at tpchgen-cli/src/parquet.rs:92:64:
called `Result::unwrap()` on an `Err` value: General("Parquet does not support more than 32767 row groups per file (currently: 32768)")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2025-03-29T11:29:15Z DEBUG tpchgen_cli::parquet] Error sending chunks to writer: channel closed
[2025-03-29T11:29:15Z DEBUG tpchgen_cli::parquet] Error sending chunks to writer: channel closed
[2025-03-29T11:29:15Z DEBUG tpchgen_cli::parquet] Error sending chunks to writer: channel closed …
```
=> Stop early on parquet write error

tpchgen-cli/src/generate.rs
- Similarly to https://github.com/clflushopt/tpchgen-rs/pull/82
If there is an error writing (like out of disk space) when writing to csv, the program generates much more data and discards it rather than stopping early
Let's stop early so tpchgen-cli can report the error quick and concisely
```
[2025-03-29T19:32:49Z DEBUG tpchgen_cli] Logging configured from environment variables
[2025-03-29T19:32:49Z DEBUG tpchgen_cli] Creating distributions and text pool
[2025-03-29T19:32:50Z INFO  tpchgen_cli] Created static distributions and text pools in 1.030596141s
[2025-03-29T19:32:50Z INFO  tpchgen_cli] Writing table lineitem (SF=100) to lineitem.tbl
[2025-03-29T19:32:50Z DEBUG tpchgen_cli] Generating 4883 parts in total
[2025-03-29T19:32:51Z DEBUG tpchgen_cli::generate] Using 22 threads …
```
=> Quit early on error for tbl/csv

tpchgen-cli/src/generate.rs, tpchgen-cli/src/main.rs
The goal of this change (Closes #77 ) is to allow writing to `stdout` which can be useful when we want to measure throughput via `pv` for example.
```
~/G/P/tpchgen-rs (cl/feat/write-to-stdout)> ./target/release/tpchgen-cli -s 100 --stdout | pv > /dev/null
106GiB 0:01:07 [1.57GiB/s]
~/G/P/tpchgen-rs (cl/feat/write-to-stdout) [SIGINT|32]> ./target/release/tpchgen-cli -s 100 --stdout | pv -arb > /dev/null
106GiB [1.36GiB/s] (1.36GiB/s)s)
```
=> feat: allow writing to stdout

tpchgen-cli/src/main.rs
Addresses an issue where short arguments collide between `parts` and `parquet-compression`.
=> fix: Use a different shorthand for parquet compression argument

README.md, tpchgen-cli/src/main.rs, tpchgen-cli/src/parquet.rs
- Follow up to https://github.com/clflushopt/tpchgen-rs/pull/83
- Related to https://github.com/clflushopt/tpchgen-rs/issues/77
I would like to also calculate raw speed for parquet generation so it would be nice to support writing parquet to stdout as well
Also, @clflushopt  showed a great command to use `pv` to measure raw output speed which I wanted to add to the readme
=> Support writing  parquet to stdout, document use of `pv`

.gitignore, tpchgen-cli/src/csv.rs, tpchgen-cli/src/generate.rs, tpchgen-cli/src/tbl.rs
- Closes https://github.com/clflushopt/tpchgen-rs/issues/73
Previously the code was generating a CSV header at the start of the chunk rather than once per file
Let's make it once per file
I tested with 
```shell
cargo run --release --  --format=csv --tables=part -s 1 --output-dir=/tmp/tpchgen-rs
datafusion-cli  -c "select * from '/tmp/tpchgen-rs/part.csv'"
```
Which works great like this:
```shell
DataFusion CLI v46.0.1
+-----------+------------------------------------------+----------------+----------+--------------------------+--------+-------------+---------------+------------------------+
| p_partkey | p_name                                   | p_mfgr         | p_brand  | p_type                   | p_size | p_container | p_retailprice | p_comment              | …
```
=> Do not generate CSV header multiple times

tpchgen-cli/src/main.rs
@clflushopt says in https://github.com/clflushopt/tpchgen-rs/issues/76#issuecomment-2764251375
> p.s: I think we should document how to pass ZSTD since it requires passing the level in a parenthesis format like this zstd(1) as such zstd\(1\) same goes for gzip which also requires a level.
So let's document it better!
=> Add documentation for zstd compression

tpchgen-cli/src/main.rs
This change closes #89 by aligning certain arguments (mainly -T,--tables) with the original `dbgen`; we do this by avoiding camel casing table names which defaults to table names being dash separated.
=> fix: Align the cli with the original dbgen

tpchgen-cli/src/main.rs
To allow supporting actual short hand we have to ensure that we use a custom TypedValueParser that is able to parse the refs correctly and align every abbrv with its long name and corresponding enum, one downside is that we lose some of the auto-derived nice things from `clap` like the list of options in the `--help` message due to a conflict from deriving `ValueEnum` vs implementing `FromStr` ourselves which is necessary to allow both abbrvs and long names.
I don't like this code because it's a lot of gymnastics for supporting command flags (I feel like clap is very much too powerful for our needs but maybe I am used to Go's stdlib provided argument handler).
There's also some non-trivial complexity in the implementation (side effect of how clap does things).
Closes #91
=> fix: Make sure table name handling is done by the crate instead of clap

tpchgen/src/generators.rs
Adds a helper method for returning a static string ("F", "O", "P") for `OrderStatus` to allow getting the string representation without needing to format it.
=> Add `as_str` helper to `OrderStatus`

tpchgen-arrow/Cargo.toml, tpchgen-cli/Cargo.toml
To make sure version compatibility stays within what we expect I am pinning the `tpchgen`crate versions for `tpchgen-cli` and `tpchgen-arrow`
=> fix: pin local crate versions

tpchgen-arrow/src/conversions.rs, tpchgen/src/dates.rs
Addresses a feature request by @scsmithr in #60 see [comment](https://github.com/clflushopt/tpchgen-rs/issues/60#issuecomment-2764785631).
The date conversion logic is largely mechanical **but it will compute everything relative to midnight**.
=> feat: add to_unix_epoch helper to TPCHDate

tpchgen-cli/src/main.rs
The help says:
```
-T, --tables <TABLES>
Which tables to generate (default: all)
Possible values:
- Region:   Region table (alias: r)
- Nation:   Nation table (alias: n)
- Supplier: Supplier table (alias: s)
- Customer: Customer table (alias: c)
- Part:     Part table (alias: P)
- PartSupp: PartSupp table (alias: S)
- Orders:   Orders table (alias: O)
- LineItem: LineItem table (alias: L)
```
However, the camelcase table names are not accepted:
```
$ tpchgen-cli --tables LineItem
```
```
error: one of the values isn't valid for an argument
For more information, try '--help'.
```
Lowercase names work fine:
```
$ tpchgen-cli --tables lineitem --verbose
```
```
[2025-04-11T20:56:01Z INFO  tpchgen_cli] Verbose output enabled (ignoring RUST_LOG environment variable)
[2025-04-11T20:56:02Z INFO …
```
=> fix: Use lowercase for possible values of table names

benchmarks/BENCHMARKS.md, benchmarks/parquet_duckdb.sh
This PR simplifies the DuckDB export code. There are no noticeable performance changes, the only difference is that the export is accompanied with a `load.sql` and a (rather redundant) `schema.sql` file.
PS: Thanks for creating and publishing this project, it's **GREAT** and I'm migrating a lot of my benchmark script to use this instead of DuckDB's built-in `dbgen` function.
=> refactor: Simplify DuckDB export

rust-toolchain.toml
By default, the CI and this project will just run using the latest stable version of Rust. This can lead to CI failures and making it hard to compile older versions of the project (as new warnings appear in newer clippy versions)
I propose adding a toolchain file to explicitly control the version
=> Add rust-toolchain.toml to control rust version

tpchgen-cli/src/main.rs
Fix up option docs based on Parser:
* `--scale` -> `--scale-factor`
* `-O, --output` -> `-o, --output-dir`
* `-F` -> `-f`
Also fixed version info:
```
tpchgen-cli -V
tpchgen-cli --version
```
Test
```
cargo run --bin tpchgen-cli -- -V
cargo run --bin tpchgen-cli -- --version
```
=> feat: fix CLI option docs

.github/workflows/rust.yml, tpchgen-cli/src/main.rs
Format issue in #127 was not caught in CI but was caught when merging. 
It looks like the github action was not run on PR. Let's fix that too
According to claude, the github action was not triggered because it [specifies `main` branch](https://github.com/clflushopt/tpchgen-rs/blob/928d57af42b3752bd7f8c211f603337611d0241f/.github/workflows/rust.yml#L6-L7) but the PR wants to merge into ` clflushopt:main`
```
kevinjqliu wants to merge 2 commits into clflushopt:main from kevinjqliu:kevinjqliu/fix-ci  
```
=> feat: fix CI and run CI for every PR

README.md
Closes #123 by documenting how to generate partitioned tables
=> fix: Document via examples the behavior of multipart generation

tpchgen-cli/README.md
Closes #130
Looks like its hard to refer to the root README from the sub directory. 
As a compromise, I added the important information back to the tpchgen-cli's README. This will be shown in the crates and pypi package.
=> Fix up `tpchgen-cli`'s README

tpchgen-cli/pyproject.toml
Related to #132
Use Cargo.toml's version which is `1.0.0` so we can push a brand new version to testpypi
Tested
```
(.venv) ➜  tpchgen-cli git:(kevinjqliu/pypi-use-cargo-version) maturin develop --release                     
🔗 Found bin bindings
📡 Using build options bindings from pyproject.toml
Finished `release` profile [optimized] target(s) in 0.11s
📦 Built wheel to /var/folders/f1/3_vzsn7x1jq9hszb3z9y6f0m0000gn/T/.tmpiNV4Gq/tpchgen_cli-1.0.0-py3-none-macosx_11_0_arm64.whl
✏️ Setting installed package as editable
🛠 Installed tpchgen-cli-1.0.0
```
=> [feat] pyproject use cargo version

.github/workflows/conformance.yml, .github/workflows/rust.yml
This PR splits the conformance test into its own action. Additionally, conformance test will be skipped for markdown file (`.md`) changes
=> [feat] skip conformance test for markdown file changes 

tpchgen/src/lib.rs, tpchgen/src/queries.rs
Add support for the TPC-H queries.
=> feat: Add TPC-H queries

tpchgen-cli/src/main.rs, tpchgen-cli/src/plan.rs, tpchgen-cli/tests/cli_integration.rs
- Closes https://github.com/clflushopt/tpchgen-rs/issues/80
=> feat: Chunkify single parts to generate them in parallel

tpchgen-cli/src/main.rs, tpchgen-cli/src/plan.rs, tpchgen-cli/tests/cli_integration.rs
Follow on to 
- https://github.com/clflushopt/tpchgen-rs/pull/155
I would like to eventually update the meaning of what `--parts` does alone, but to do that reasonably I would like the code in better shape to represent what is going on
1. Return an error if only one of `--part` or `--parts` is specified
2. Make `--part` and `--parts` `Option`
3. test error conditions
=> refactor: Make `--part` and `--parts` `Option<i32>` and add better error handling

.github/workflows/tpchgen-cli-publish-pypi.yml
Context: https://github.com/clflushopt/tpchgen-rs/issues/172#issuecomment-3228025491
When any wheel build fails, continue to build the rest of the wheels and publish to pypi
Not 100% sure if we want this behavior...
Worst case scenario, only one wheel is successfully built. The version is released on pypi with 1 wheel. Since pypi artifacts are immutable, we'd have to fix the underlying issue, increase the version, and start a new release
=> infra: add `continue-on-error: true` to the wheel builds
